### ISSUE TITLE
Finalize Icon Choice

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#967]
We settled on using the icon from @net. In #863, some changes were discussed including using the blue flame variant, and tweaking the stroke to make it show up better on dark backgrounds.

## Tasks

- [ ] @net to tweak border
- [ ] @net to provide final SVG
- [ ] Ship icon for macOS
- [ ] Ship icon for Linux

**Comment by Iambecomeroot** [comment]
Any updates on this?

**Comment by chrisduerr** [comment]
As far as I know we're still waiting on @net to make the requested changes and provide the final SVG.

As far as I know he did not provide any licensing information and there also is no SVG we could work with. So unless we can get a hold of him we'd probably need to design something new.

**Comment by jedahan** [comment]
I'd love as an easter egg, to be able to keep the current variant as well, but yknow, there are definitely higher priorities.

**Comment by chrisduerr** [comment]
If @net is not available for providing the icon we chose, we might have to look for a new icon?

Maybe open up a RFC or something like this? I doubt that this issue will progress anytime soon.

**Comment by chrisduerr** [comment]
With permission of @net I've tried to reproduce the icon he's designed as an SVG (since the original was not an SVG).

Here are the results I was able to achieve:

Scanlines + Background:
![Scanlines + Background](https://u.teknik.io/1Yoml.svg)

Background:
![Background](https://u.teknik.io/UP66N.svg)

Without Background:
![No Background](https://u.teknik.io/pJZCA.svg)

**Comment by liamdawson** [comment]
Any progress on this? I'd love to replace the generic X11 icon I get on Linux when alt-tabbing to Alacritty.

**Comment by zacps** [comment]
Just commenting here to make note that the icon Alacritty uses on windows is `assets/windows/alacritty.ico` and MUST be a `.ico` file, so whatever gets chosen should be converted.

**Comment by musm** [comment]
How come my icon does not look anything like the ones posted here
![image](https://user-images.githubusercontent.com/4319522/55971577-bd52c200-5c4f-11e9-9631-966726fde3dd.png)

in fact it seems to be wrong in terms of the pixel size (blurry, probably due to scaling issue)

**Comment by chrisduerr** [comment]
The white background should be fixed with the latest master. There are some scaling issues with Windows but that seems to be because of issues with the .ico format.
